kubectl delete -f step10_kibana.yaml
kubectl delete -f step9_agent_ship_logs_logstash.yaml
kubectl delete -f step8_logstash_service.yaml
kubectl delete -f step7_logstash_deployment.yaml
kubectl delete -f step6_logstash_configmap.yaml
kubectl delete -f step4_es_service.yaml
kubectl delete -f step3_es_sts.yaml
kubectl delete -f step2_rbac.yaml
kubectl delete -f step1_rbac.yaml
